name: Tracking Issue (Internal Only)
description: Lightweight tracking issue that is not suitable for a PRD
title: "tracking: Example Initiative"
labels:
  - epic

body:
  - type: markdown
    attributes:
      value: |
        > [!note]
        > Title must have prefix `tracking:`
        > This is an epic-style issue for tracking/grouping issues only, used to track high level priorities.

  - type: textarea
    id: Description
    attributes:
      label: "Description:"
      description: What is the problem we are trying to solve?
      value: |
        <!-- Example: Tracking issue for measuring chat usage -->
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: "Tasks related to this epic"
      description: DO NOT REMOVE - EPD to fill out
      value: |
        ```[tasklist]
        ### Tasks
        - [ ] replace-with-your-task
        ```
  - type: textarea
    id: related-docs
    attributes:
      label: "Related Docs:"
      value: |
        - [PRD: Your-Title]()
